version: "2.4"

services:
  db:
    container_name: sickfits-backend
    image: postgres:14.2-alpine
    restart: always
    ports:
      - 5777:5432
    volumes:
      - sickfits-backend:/var/lib/postgresql
    environment:
      POSTGRES_USER: sickfits
      POSTGRES_PASSWORD: sickfits
      POSTGRES_DB: sickfits

volumes:
  sickfits-backend:
